"""Added User images column

Revision ID: 380d260f1969
Revises: 30b9c0e8a9e7
Create Date: 2013-12-30 04:35:45.493451

"""

# revision identifiers, used by Alembic.
revision = '380d260f1969'
down_revision = '30b9c0e8a9e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_images')
    ### end Alembic commands ###
