"""added thumbnail column

Revision ID: 399148820ece
Revises: 380d260f1969
Create Date: 2013-12-30 06:06:31.104197

"""

# revision identifiers, used by Alembic.
revision = '399148820ece'
down_revision = '380d260f1969'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('thumbnail', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_images', 'thumbnail')
    ### end Alembic commands ###
