"""added tag model

Revision ID: 5adf228cb1c5
Revises: ec312049b22
Create Date: 2013-12-31 20:13:34.785086

"""

# revision identifiers, used by Alembic.
revision = '5adf228cb1c5'
down_revision = 'ec312049b22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=30), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tags')
    ### end Alembic commands ###
