"""added showcase field

Revision ID: ec312049b22
Revises: 399148820ece
Create Date: 2013-12-30 10:56:32.100599

"""

# revision identifiers, used by Alembic.
revision = 'ec312049b22'
down_revision = '399148820ece'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('showcase', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_images', 'showcase')
    ### end Alembic commands ###
